eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082

spring:
  application:
    name: Product-Service
  cloud:
    config:
      uri: http://localhost:8889
